version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currencies
    ports:
      - "5432:5432"
  migrations:
    build:
      context: .
      dockerfile: src/MigrationsService/Dockerfile
    environment:
      Database__Host: postgres
      Database__Port: 5432
      Database__Database: currencies
      Database__Username: postgres
      Database__Password: postgres
    depends_on:
      - postgres
  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    environment:
      Database__Host: postgres
      Database__Port: 5432
      Database__Database: currencies
      Database__Username: postgres
      Database__Password: postgres
      Jwt__Issuer: RightCodeTestTask
      Jwt__Audience: RightCodeTestTask
      Jwt__Secret: super_secret_key_for_demo_only_change_me
    ports:
      - "5001:5001"
    depends_on:
      - migrations
  finance-service:
    build:
      context: .
      dockerfile: src/FinanceService/Dockerfile
    environment:
      Database__Host: postgres
      Database__Port: 5432
      Database__Database: currencies
      Database__Username: postgres
      Database__Password: postgres
      Services__UserService: http://user-service:5001
      Jwt__Issuer: RightCodeTestTask
      Jwt__Audience: RightCodeTestTask
      Jwt__Secret: super_secret_key_for_demo_only_change_me
    ports:
      - "5002:5002"
    depends_on:
      - migrations
  worker:
    build:
      context: .
      dockerfile: src/BackgroundWorker/Dockerfile
    environment:
      Database__Host: postgres
      Database__Port: 5432
      Database__Database: currencies
      Database__Username: postgres
      Database__Password: postgres
    depends_on:
      - migrations
  gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - finance-service
